/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { L2Bridge } from "./L2Bridge";
export * as factories from "./factories";
export { L2Bridge__factory } from "./factories/L2Bridge__factory";
